// A page is a cached procedural asset, not a downloaded mesh. Morton-ordered BVH leaves
// refer to analytic primitives generated by assets.cu. All accesses stay on the GPU.
__global__ void sortPages(const int* Queue,const float* P,int* Order,float* Nodes){
 __shared__ unsigned int keys[PRIMS];
 __shared__ unsigned int ids[PRIMS];
 int q=(int)blockIdx.x;int lane=(int)threadIdx.x;bool valid=q<Queue[0];int slot=0;
 if(valid)slot=Queue[q+1];
 for(int r=0;r<PRIMS/256;r++){
  int i=lane+r*256;unsigned int key=4294967295u;
  if(valid){int b=(slot*PRIMS+i)*PS;if(P[b+3]>=0.0f){float cx=floorf((P[b]+CELL*0.5f)/CELL)*CELL;float cz=floorf((P[b+2]+CELL*0.5f)/CELL)*CELL;key=morton3((P[b]-cx+18.0f)/36.0f,P[b+1]/70.0f,(P[b+2]-cz+18.0f)/36.0f);}}
  keys[i]=key;ids[i]=(unsigned int)i;
 }
 __syncthreads();
 for(int size=2;size<=PRIMS;size*=2){
  for(int stride=size/2;stride>0;stride/=2){
   for(int r=0;r<PRIMS/256;r++){
    int i=lane+r*256;int other=i^stride;
    if(other>i){bool ascending=(i&size)==0;unsigned int a=keys[i];unsigned int b=keys[other];unsigned int ia=ids[i];unsigned int ib=ids[other];
     bool greater=a>b||(a==b&&ia>ib);
     if((ascending&&greater)||(!ascending&&!greater)){keys[i]=b;keys[other]=a;ids[i]=ib;ids[other]=ia;}
    }
   }
   __syncthreads();
  }
 }
 if(valid)for(int r=0;r<PRIMS/256;r++){
  int i=lane+r*256;int id=slot*PRIMS+(int)ids[i];Order[slot*PRIMS+i]=id;int b=id*PS;int n=(slot*NODES+PRIMS+i)*8;
  float3 lo=make_float3(1000000.0f,1000000.0f,1000000.0f);float3 hi=make_float3(-1000000.0f,-1000000.0f,-1000000.0f);
  if(P[b+3]>=0.0f){
   float3 p=make_float3(P[b],P[b+1],P[b+2]);float3 h=make_float3(P[b+4],P[b+5],P[b+6]);
   if(((int)P[b+8])%2==1){float tmp=h.x;h.x=h.z;h.z=tmp;}
   lo=p-h;hi=p+h;if((int)P[b+3]==3||(int)P[b+3]==4)lo.y=p.y;
   lo=lo-make_float3(0.008f,0.008f,0.008f);hi=hi+make_float3(0.008f,0.008f,0.008f);
  }
  Nodes[n]=lo.x;Nodes[n+1]=lo.y;Nodes[n+2]=lo.z;Nodes[n+3]=P[b+3]>=0.0f?1.0f:0.0f;
  Nodes[n+4]=hi.x;Nodes[n+5]=hi.y;Nodes[n+6]=hi.z;Nodes[n+7]=0.0f;
 }
}
__global__ void buildBVH(const int* Queue,float* Nodes,int first){
 int i=(int)(blockIdx.x*blockDim.x+threadIdx.x);int q=i/first;int j=i%first+first;if(q>=Queue[0])return;
 int slot=Queue[q+1];int n=(slot*NODES+j)*8;int a=(slot*NODES+j*2)*8;int b=a+8;
 for(int k=0;k<3;k++){Nodes[n+k]=fminf(Nodes[a+k],Nodes[b+k]);Nodes[n+4+k]=fmaxf(Nodes[a+4+k],Nodes[b+4+k]);}
 Nodes[n+3]=Nodes[a+3]+Nodes[b+3];Nodes[n+7]=0.0f;
}
